# Generated by Django 5.2.6 on 2025-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('doctor', 'Doctor'), ('queue', 'Queue')], max_length=20),
        ),
    ]
