# Generated by Django 5.2.6 on 2025-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_accesstoken_password_alter_accesstoken_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='role',
            field=models.CharField(choices=[('form', 'Form'), ('doctor', 'Doctor'), ('queue', 'Queue')], max_length=20),
        ),
    ]
