# Generated by Django 5.2.6 on 2025-10-17 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_accesstoken_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('pronoun', models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('ssn', models.CharField(blank=True, max_length=9, null=True)),
                ('street1', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('last_known_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('medicaid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('lost/stolen', 'LOST/STOLEN')], help_text='Do you have a valid ID card?', max_length=100, null=True)),
                ('insurance', models.CharField(blank=True, choices=[('humana', 'Humana'), ('aetna', 'Aetna'), ('magellan', 'Magellan'), ('anthem', 'Anthem'), ('sentara', 'Sentara'), ('united', 'United')], max_length=255, null=True)),
                ('race', models.CharField(blank=True, choices=[('black_african_american', 'Black/African American'), ('caucasian', 'Caucasian'), ('hispanic_latino', 'Hispanic/Latino'), ('american_indian_or_alaskan_native', 'American Indian or Alaskan Native'), ('biracial', 'Biracial'), ('asian', 'Asian'), ('hawaiian_pacific_islander', 'Hawaiian/Pacific Islander')], help_text='Race (e.g., Asian, Black/African American, etc.)', max_length=50, null=True)),
                ('pref_service', models.CharField(blank=True, choices=[('yes', 'YES'), ('yes', 'NO'), ('lost/stolen', 'LOST/STOLEN')], max_length=255, null=True)),
                ('pref_service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('employed', models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No'), ('disabled', 'Disabled')], default=False, help_text='Are you employed?')),
                ('shower', models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=False, help_text='Do you need a shower?', null=True)),
                ('hungry', models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default=False, help_text='Are you hungry?')),
                ('homeless', models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('staying/someone', 'Staying / Someone')], default=False, help_text='Are you homeless?', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='patient_images/')),
                ('wait_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='management.patient')),
            ],
            options={
                'ordering': ['check_in_time'],
            },
        ),
    ]
