# Generated by Django 5.2.6 on 2025-10-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='employed',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('disabled', 'Disabled')], default='no', help_text='Are you employed?', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='homeless',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('staying/someone', 'Staying / Someone')], default='no', help_text='Are you homeless?', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hungry',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Are you hungry?', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='shower',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Do you need a shower?', null=True),
        ),
    ]
