# Generated by Django 5.2.6 on 2025-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_patient_employed_alter_patient_homeless_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='employed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('disabled', 'Disabled')], default='NO', help_text='Are you employed?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='homeless',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('staying/someone', 'Staying / Someone')], default='Yes', help_text='Are you homeless?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hungry',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='No', help_text='Are you hungry?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='shower',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='No', help_text='Do you need a shower?', max_length=100, null=True),
        ),
    ]
