# Generated by Django 5.2.6 on 2025-10-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_patient_employed_alter_patient_homeless_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pref_service',
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicaid_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pref_service_area',
            field=models.CharField(blank=True, choices=[('east_end', 'East End'), ('west_end', 'West End'), ('chesterfield', 'Chesterfield'), ('chester', 'Chester'), ('colonial_heights', 'Colonial Heights'), ('north_side_richmond', 'North side Richmond'), ('southside_richmond', 'Southside Richmond'), ('church_hill', 'Church Hill'), ('ashland', 'Ashland'), ('hopewell', 'Hopewell')], help_text='Preferred Service Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, choices=[('black_african_american', 'Black/African American'), ('caucasian', 'Caucasian'), ('hispanic_latino', 'Hispanic/Latino'), ('american_indian_or_alaskan_native', 'American Indian or Alaskan Native'), ('biracial', 'Biracial'), ('asian', 'Asian'), ('hawaiian_pacific_islander', 'Hawaiian/Pacific Islander'), ('other', 'Other')], help_text='Race (e.g., Asian, Black/African American, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
