# Generated by Django 5.2.6 on 2025-10-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_patient_pref_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
