# Generated by Django 5.2.6 on 2025-10-28 22:39

from django.db import migrations, models


def copy_sitesettings_to_adminlist(apps, schema_editor):
    SiteSettings = apps.get_model('management', 'SiteSettings')
    AdminGmailList = apps.get_model('management', 'AdminGmailList')
    try:
        qs = SiteSettings.objects.all().order_by('-updated_at', '-id')
        obj = qs.exclude(admin_recipients__isnull=True).exclude(admin_recipients__exact='').first() or qs.first()
        if obj:
            AdminGmailList.objects.create(admin_recipients=obj.admin_recipients)
    except Exception:
        # If old table doesn't exist or any error occurs, just skip
        pass


def copy_adminlist_to_sitesettings(apps, schema_editor):
    """Reverse migration: attempt to recreate SiteSettings from AdminGmailList."""
    SiteSettings = apps.get_model('management', 'SiteSettings')
    AdminGmailList = apps.get_model('management', 'AdminGmailList')
    try:
        obj = AdminGmailList.objects.all().order_by('-updated_at', '-id').first()
        if obj:
            SiteSettings.objects.create(admin_recipients=obj.admin_recipients)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('admin_recipients', models.TextField(blank=True, default='', help_text='Comma-separated list of recipient email addresses for admin notifications.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Gmail List',
                'verbose_name_plural': 'Admin Gmail List',
            },
        ),
        migrations.RunPython(copy_sitesettings_to_adminlist, copy_adminlist_to_sitesettings),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
