# Generated by Django 5.2.6 on 2025-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_admingmaillist_delete_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='employed',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO'), ('disabled', 'DISABLED'), ('retired', 'RETIRED')], default='no', help_text='Are you employed?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='homeless',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='yes', help_text='Are you homeless?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hungry',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', help_text='Are you hungry?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_card',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO'), ('lost', 'LOST/STOLEN')], help_text='Do you have a valid ID card?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('humana', 'Humana'), ('aetna', 'Aetna'), ('magellan', 'Magellan'), ('anthem', 'Anthem'), ('sentara', 'Sentara'), ('united', 'United'), ('dont_know', "I Don't Know")], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pref_service_area',
            field=models.CharField(blank=True, choices=[('petersburg', 'Petersburg'), ('east_end', 'East End'), ('west_end', 'West End'), ('chesterfield', 'Chesterfield'), ('chester', 'Chester'), ('colonial_heights', 'Colonial Heights'), ('north_side_richmond', 'North side Richmond'), ('southside_richmond', 'Southside Richmond'), ('church_hill', 'Church Hill'), ('ashland', 'Ashland'), ('hopewell', 'Hopewell')], help_text='Preferred Service Area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('he_him', 'He/Him'), ('she_her', 'She/Her'), ('they_them', 'They/Them'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, choices=[('black_african_american', 'Black/African American'), ('caucasian', 'Caucasian'), ('hispanic_latino', 'Hispanic/Latino'), ('american_indian_alaskan_native', 'American Indian or Alaskan Native'), ('biracial', 'Biracial'), ('asian', 'Asian'), ('middle_eastern', 'Middle Eastern'), ('hawaiian_pacific_islander', 'Hawaiian/Pacific Islander'), ('other', 'Other')], help_text='Race (e.g., Asian, Black/African American, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='shower',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', help_text='Do you need a shower?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, choices=[('VA', 'Virginia'), ('MD', 'Maryland'), ('NC', 'North Carolina'), ('SC', 'South Carolina')], max_length=100, null=True),
        ),
    ]
